### PR TITLE
test worker instead of slave

### PR DESCRIPTION
**Pull request by tardyp**

### CODE REVIEW

**Comment by rutsky** [comment]
Linter yells:

```
./status.py:3:1: E402 module level import not at top of file

from buildbot.status import html

^

./status.py:4:1: E402 module level import not at top of file

from buildbot.status import words

^

./status.py:5:1: E402 module level import not at top of file

from buildbot.status.web.auth import BasicAuth

^

./status.py:6:1: E402 module level import not at top of file

from buildbot.status.web.authz import Authz

^

4       E402 module level import not at top of file

4
```

**Comment by tomprince** [comment]
The lint failures are due to flake8 2.6 (see #45).

**Comment by tomprince** [comment]
@tardyp: Thanks for fixing this up.

**Comment by tardyp** [comment]
@tomprince good teamwork

**Pull request merged**
