### PR TITLE
recreate the virtualenv if it is too old

### PR DESCRIPTION
**Pull request by tardyp**

### CODE REVIEW

**Comment by djmitche** [comment]
It seems like doing this on a time basis may lead to flakiness, where things fail for 5 days then suddenly get better.  That's better than failing forever, of course :)

Could some kind of semaphore file in the Buildbot source code be used instead?  So we could "bump" that file (set it to the curent unix epoch, for example) to convince the workers to erase and re-create their virtualenvs?

**Comment by sa2ajj** [comment]
why not create a virtualenv *every* time?

**Comment by tardyp** [comment]
Because pip install everything is very slow.

That said, now pip is building and caching wheels for everything, maybe we
can indeed recreate the env each time
that would please koobs who was complaining 300MB per builder was too much
space


Le dim. 31 juil. 2016 à 08:04, Mikhail Sobolev <notifications@github.com> a
écrit :

**Comment by sa2ajj** [comment]
Well, to optimise virtualenv creation, one could create the necessary virtualenv, store it, and unpack whenever it's necessary.  The updates could be done out-of-bound....

The tricky thing is, of course, to make sure that "unpacking" happens at the exactly correct path, virtualenv is notorious for not being relocatable....

**Pull request merged**
